# Generated by Django 3.0.2 on 2020-01-21 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('project_name', models.CharField(help_text='Nombre del proyecto', max_length=120, verbose_name='Proyecto')),
                ('number_of_bedrooms', models.FloatField(default=1, help_text='Número de cuartos (Ej. 1, 1.5, 2, etc)', verbose_name='Cuartos')),
                ('number_of_bathrooms', models.FloatField(default=1, help_text='Número de Baños (Ej. 1, 1.5, 2, etc)', verbose_name='Baños')),
                ('number_of_parking_lots', models.PositiveIntegerField(default=1, help_text='Cajones de estacionamiento', verbose_name='Estacionamiento')),
                ('is_active', models.BooleanField(default=True, help_text='Proyecto activo', verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('state_name', models.CharField(max_length=120, verbose_name='Nombre de Estado')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
            },
        ),
        migrations.CreateModel(
            name='TownHall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('town_hall_name', models.CharField(max_length=120, verbose_name='Nombre de Alcaldía')),
                ('state', models.ForeignKey(help_text='Elija un Estado', on_delete=django.db.models.deletion.CASCADE, to='projects.State', verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Alcaldía',
                'verbose_name_plural': 'Alcaldías',
            },
        ),
        migrations.CreateModel(
            name='Suburb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('suburb_name', models.CharField(max_length=120, verbose_name='Colonia')),
                ('town_hall', models.ForeignKey(help_text='Elija una Alcaldía', on_delete=django.db.models.deletion.CASCADE, to='projects.TownHall', verbose_name='Alcaldía')),
            ],
            options={
                'verbose_name': 'Colonia',
                'verbose_name_plural': 'Colonias',
            },
        ),
        migrations.CreateModel(
            name='ProjectRenders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
            options={
                'verbose_name': 'Render',
                'verbose_name_plural': 'Renders',
            },
        ),
        migrations.CreateModel(
            name='ProjectConstructionPlans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
            options={
                'verbose_name': 'Plano de Construcción',
                'verbose_name_plural': 'Planos de Construcción',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='suburb',
            field=models.ForeignKey(help_text='Elija una colonia', on_delete=django.db.models.deletion.CASCADE, to='projects.Suburb', verbose_name='Colonia'),
        ),
    ]
