# Generated by Django 3.0.2 on 2020-01-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pre_sale',
            field=models.BooleanField(default=True, verbose_name='Pre Venta'),
        ),
    ]
