# Generated by Django 3.0.2 on 2020-01-17 23:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locality',
            options={'verbose_name': 'Localidad', 'verbose_name_plural': 'Localidades'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'verbose_name': 'Estado', 'verbose_name_plural': 'Estados'},
        ),
        migrations.AddField(
            model_name='project',
            name='active_from',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='project',
            name='active_until',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='project',
            name='number_of_bathrooms',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='project',
            name='number_of_bedrooms',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='project',
            name='number_of_parking_lots',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='ProjectRenders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
            options={
                'verbose_name': 'Render',
                'verbose_name_plural': 'Renders',
            },
        ),
    ]
