# Generated by Django 3.0.2 on 2020-01-28 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='address',
            field=models.CharField(blank=True, help_text='Dirección obtenida de la Url de Google Maps. Se generará automáticamente', max_length=300, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='project',
            name='url_location',
            field=models.URLField(blank=True, help_text='URL de Google Maps con la ubicación, asegúrese de que sea una dirección valida.', max_length=300, null=True, verbose_name='Url de Ubicación'),
        ),
    ]
