# Generated by Django 3.0.2 on 2020-01-27 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('id',), 'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
        migrations.AddField(
            model_name='project',
            name='url_location',
            field=models.URLField(default=None, help_text='URL de Google Maps con la ubicación', max_length=300, null=True, verbose_name='Ubicación'),
        ),
    ]
