# Generated by Django 3.0.2 on 2020-01-17 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200117_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='active_from',
        ),
        migrations.RemoveField(
            model_name='project',
            name='active_until',
        ),
        migrations.AddField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
