# Generated by Django 3.0.2 on 2020-01-27 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200126_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='latitude',
            field=models.CharField(blank=True, help_text='Deje este campo vacío, se calculará con la url de Google Maps', max_length=20, null=True, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='project',
            name='longitude',
            field=models.CharField(blank=True, help_text='Deje este campo vacío, se calculará con la url de Google Maps', max_length=20, null=True, verbose_name='Longitud'),
        ),
    ]
