# Generated by Django 3.0.2 on 2020-02-07 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_pre_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectvariants',
            name='construction_plane',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Planos de contrucción'),
        ),
        migrations.DeleteModel(
            name='ProjectConstructionPlans',
        ),
    ]
