# Generated by Django 3.0.2 on 2020-02-07 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200206_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectvariants',
            name='has_comunal_roof',
            field=models.BooleanField(default=False, help_text='Tiene Roof Comunal', verbose_name='Roof Garden Comunal'),
        ),
        migrations.AlterField(
            model_name='projectvariants',
            name='has_private_roof',
            field=models.BooleanField(default=False, help_text='Tiene Roof Privado', verbose_name='Roof Garden Privado'),
        ),
    ]
