# Generated by Django 3.0.2 on 2020-02-07 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20200206_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('area', models.FloatField(default=1, verbose_name='Superficie')),
                ('habitable_area', models.FloatField(blank=True, default=1, null=True, verbose_name='Superficie Habitable')),
                ('number_of_bedrooms', models.FloatField(default=1, help_text='Número de cuartos (Ej. 1, 1.5, 2, etc)', verbose_name='Cuartos')),
                ('number_of_bathrooms', models.FloatField(default=1, help_text='Número de Baños (Ej. 1, 1.5, 2, etc)', verbose_name='Baños')),
                ('number_of_parking_lots', models.PositiveIntegerField(default=1, help_text='Cajones de estacionamiento', verbose_name='Estacionamiento')),
                ('has_comunal_roof', models.BooleanField(default=False, help_text='Tiene Roof Comunal', verbose_name='Roof Garden Comunal')),
                ('private_roof_size', models.FloatField(default=0, verbose_name='Tamaño del Roof Garden Privado')),
                ('has_private_roof', models.BooleanField(default=False, help_text='Tiene Roof Privado', verbose_name='Roof Garden Privado')),
                ('comunal_roof_size', models.FloatField(default=0, verbose_name='Tamaño del Roof Garden Comunal')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='Precio')),
                ('construction_plane', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Planos del departamento')),
                ('project', models.ForeignKey(help_text='Elija un proyecto', on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ('id',),
            },
        ),
        migrations.DeleteModel(
            name='ProjectVariants',
        ),
    ]
