# Generated by Django 3.0.2 on 2020-02-07 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20200206_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='apartment_number',
            field=models.CharField(blank=True, default='', max_length=8, null=True, verbose_name='Número de departamento'),
        ),
    ]
